### ISSUE TITLE
Add buildings from ONI Automation Mod google sheet

### ISSUE THREAD

**Issue by Hexicube** [Hexicube/ONI-DenseLogic#5]
https://docs.google.com/spreadsheets/d/1t8YedOcIuAwYI9n6xs-9Is49czvrBJLM9Su9iDTzyJU

- [x] Condensed Multiplexer (bundle in single out / single in bundled out)
- [x] Signal Re-arranger (allows swapping bits)
- [x] Inline Logic Gate (perform logic with bits on a ribbon, 1x1)
- [x] Dense Logic Gate (logic gates that use bundled wires)
- [ ] Binary Sensor (bundled in, single out, out is true if bundle binary exceeds value)
- [x] D-Latch
- [x] Digitizer (bundle binary in to 7-seg out)
- [x] NAND/NOR/NXOR Gates
- [ ] Nixie Tubes (could merge into Digitizer, bundle binary in to visual out)
- [x] Bundled Switch (4-bit version of basic switch)
- [x] Multi Logic Gates (Dense Logic Gate mode toggle for basic gates)
- [ ] Edge Detector (send pulse on specific state change)

**Comment by daviscook477** [comment]
We can probably kill the Ribbon Bridge. Basic automation bridges currently work with ribbon cable without signal overload damage. We can't really be sure if this is intentional until Klei themselves clarify.
From today's update post by Klei it's pretty clear they're not entirely sure how this automation stuff should work themselves. So I'd take that as another reason to probably hold off on releasing anything on the workshop until this update leaves the beta branch.
